version: '3.8'

services:
  ubuntu-vscode-filemanager:
    build:
      context: .
      dockerfile: "/src/main/java/com/cloudcode/docker/dockerfile"
    container_name: ${CONTAINER_NAME}
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
